### ISSUE TITLE
Updating the Demo code

### ISSUE THREAD

**Issue by timoknapp** [jakobehn/azurecontainerapp-demo#1]
Hi @jakobehn ,

thanks again for hosting the session in the Cloud Native Series this week, I really liked your presentation and the way you introduced Azure Container Apps. I just had a look into the current code and it seems that during the session you had a more recent version of the code than its pushed to GitHub. I am actually looking for the `.bicep` files you showed in the session, but they are missing in the repo. Do you mind pushing the latest version of it?

![1067D54A-CE67-45A5-B26B-30D47CB4BC9E](https://user-images.githubusercontent.com/11437666/154796354-5ed0117d-7ae1-4d8f-9e0e-3fcc84c38a4a.jpeg)

Regards
Timo

**Comment by jakobehn** [comment]
Hi Timo, thanks for the nice feedback, much appreciated!

You are right, I accidentally missed to publish the bicep files when I moved the demo repo to GitHub. I just updated it now with the missing files.

Thanks
/Jakob

**Comment by timoknapp** [comment]
Hi Jakob,

thanks for the quick feedback. I will have a look into the code.
Thanks again!

Timo.
